# Generated by Django 2.2.23 on 2021-07-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('cancer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancer_type', models.CharField(max_length=25, verbose_name='Cancer Type')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalIndication',
            fields=[
                ('ci_code', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='CI Code')),
                ('ci_name', models.TextField(verbose_name='CI Name')),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.CancerType', verbose_name='Cancer Type')),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('scope_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_scope', models.CharField(max_length=150, verbose_name='Test Scope')),
            ],
            options={
                'ordering': ['test_scope'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=100, verbose_name='Target')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('technology', models.CharField(max_length=50, verbose_name='Technology')),
            ],
            options={
                'ordering': ['technology'],
            },
        ),
        migrations.CreateModel(
            name='GenomicTest',
            fields=[
                ('test_code', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Test Code')),
                ('test_name', models.TextField(verbose_name='Test Name')),
                ('targets', models.TextField(verbose_name='Targets')),
                ('eligibility', models.TextField(verbose_name='Eligibility Criteria')),
                ('ci_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.ClinicalIndication', verbose_name='CI Code')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.Technology', verbose_name='Technology')),
                ('test_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.Scope', verbose_name='Test Scope')),
            ],
        ),
    ]
