# Generated by Django 2.2.23 on 2021-07-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerTypeJul21',
            fields=[
                ('cancer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancer_type', models.CharField(max_length=25, verbose_name='Cancer Type')),
            ],
        ),
        migrations.CreateModel(
            name='CancerTypeNov20',
            fields=[
                ('cancer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancer_type', models.CharField(max_length=25, verbose_name='Cancer Type')),
            ],
        ),
        migrations.CreateModel(
            name='CITTJul21',
            fields=[
                ('citt_id', models.AutoField(primary_key=True, serialize=False)),
                ('citt_comment', models.TextField(verbose_name='CITT Comment')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalIndicationJul21',
            fields=[
                ('ci_code', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='CI Code')),
                ('ci_name', models.TextField(verbose_name='CI Name')),
                ('cancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.CancerTypeJul21', verbose_name='Cancer Type')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalIndicationNov20',
            fields=[
                ('ci_code', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='CI Code')),
                ('ci_name', models.TextField(verbose_name='CI Name')),
                ('cancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.CancerTypeNov20', verbose_name='Cancer Type')),
            ],
        ),
        migrations.CreateModel(
            name='CommissioningCategoryJul21',
            fields=[
                ('cc_id', models.AutoField(primary_key=True, serialize=False)),
                ('commissioning', models.CharField(max_length=10, verbose_name='Commissioning Category')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentlyProvidedJul21',
            fields=[
                ('provided_id', models.AutoField(primary_key=True, serialize=False)),
                ('provided', models.CharField(max_length=15, verbose_name='Currently Provided')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentlyProvidedNov20',
            fields=[
                ('provided_id', models.AutoField(primary_key=True, serialize=False)),
                ('provided', models.CharField(max_length=15, verbose_name='Currently Provided')),
            ],
        ),
        migrations.CreateModel(
            name='DesirableTargetLinksJul21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EssentialTargetLinksJul21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EssentialTargetLinksNov20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyStructureJul21',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_structure', models.CharField(max_length=10, verbose_name='Optimal Family Structure')),
            ],
        ),
        migrations.CreateModel(
            name='InHouseTestJul21',
            fields=[
                ('inhouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('inhouse', models.CharField(max_length=100, verbose_name='In-House Test')),
            ],
            options={
                'ordering': ['inhouse'],
            },
        ),
        migrations.CreateModel(
            name='InHouseTestNov20',
            fields=[
                ('inhouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('inhouse', models.CharField(max_length=100, verbose_name='In-House Test')),
            ],
            options={
                'ordering': ['inhouse'],
            },
        ),
        migrations.CreateModel(
            name='ScopeJul21',
            fields=[
                ('scope_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_scope', models.CharField(max_length=150, verbose_name='Test Scope')),
            ],
            options={
                'ordering': ['test_scope'],
            },
        ),
        migrations.CreateModel(
            name='ScopeNov20',
            fields=[
                ('scope_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_scope', models.CharField(max_length=150, verbose_name='Test Scope')),
            ],
            options={
                'ordering': ['test_scope'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistJul21',
            fields=[
                ('specialist_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialist_group', models.CharField(max_length=25, verbose_name='Specialist Test Group')),
            ],
        ),
        migrations.CreateModel(
            name='TargetJul21',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=100, verbose_name='Target')),
            ],
        ),
        migrations.CreateModel(
            name='TargetNov20',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=100, verbose_name='Target')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyJul21',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('technology', models.CharField(max_length=50, verbose_name='Technology')),
            ],
            options={
                'ordering': ['technology'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyNov20',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('technology', models.CharField(max_length=50, verbose_name='Technology')),
            ],
            options={
                'ordering': ['technology'],
            },
        ),
        migrations.CreateModel(
            name='TTJul21',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('tt_code', models.CharField(max_length=10, verbose_name='TT Code')),
            ],
        ),
        migrations.CreateModel(
            name='GenomicTestNov20',
            fields=[
                ('test_code', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Test Code')),
                ('test_name', models.TextField(verbose_name='Test Name')),
                ('eligibility', models.TextField(verbose_name='Eligibility Criteria')),
                ('ci_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.ClinicalIndicationNov20', verbose_name='CI Code')),
                ('inhouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.InHouseTestNov20', verbose_name='In-House Test')),
                ('provided_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.CurrentlyProvidedNov20', verbose_name='Currently Provided')),
                ('scope_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.ScopeNov20', verbose_name='Test Scope')),
                ('targets_essential', models.ManyToManyField(related_name='EssentialTargetLinks_related', through='ngtdc_db.EssentialTargetLinksNov20', to='ngtdc_db.TargetNov20', verbose_name='Targets (Essential)')),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.TechnologyNov20', verbose_name='Technology')),
            ],
        ),
        migrations.CreateModel(
            name='GenomicTestJul21',
            fields=[
                ('test_code', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Test Code')),
                ('test_name', models.TextField(verbose_name='Test Name')),
                ('eligibility', models.TextField(verbose_name='Eligibility Criteria')),
                ('cc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.CommissioningCategoryJul21', verbose_name='Commissioning Category')),
                ('ci_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.ClinicalIndicationJul21', verbose_name='CI Code')),
                ('citt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.CITTJul21', verbose_name='CITT Comment')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.FamilyStructureJul21', verbose_name='Optimal Family Structure')),
                ('inhouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.InHouseTestJul21', verbose_name='In-House Test')),
                ('provided_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.CurrentlyProvidedJul21', verbose_name='Currently Provided')),
                ('scope_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.ScopeJul21', verbose_name='Test Scope')),
                ('specialist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.SpecialistJul21', verbose_name='Specialist Test Group')),
                ('targets_desirable', models.ManyToManyField(related_name='DesirableTargetLinks_related', through='ngtdc_db.DesirableTargetLinksJul21', to='ngtdc_db.TargetJul21', verbose_name='Targets (Desirable)')),
                ('targets_essential', models.ManyToManyField(related_name='EssentialTargetLinks_related', through='ngtdc_db.EssentialTargetLinksJul21', to='ngtdc_db.TargetJul21', verbose_name='Targets (Essential)')),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.TechnologyJul21', verbose_name='Technology')),
                ('tt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.TTJul21', verbose_name='TT Code')),
            ],
        ),
        migrations.AddField(
            model_name='essentialtargetlinksnov20',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.TargetNov20', verbose_name='Target'),
        ),
        migrations.AddField(
            model_name='essentialtargetlinksnov20',
            name='test_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.GenomicTestNov20', verbose_name='Test Code'),
        ),
        migrations.AddField(
            model_name='essentialtargetlinksjul21',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.TargetJul21', verbose_name='Target'),
        ),
        migrations.AddField(
            model_name='essentialtargetlinksjul21',
            name='test_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.GenomicTestJul21', verbose_name='Test Code'),
        ),
        migrations.AddField(
            model_name='desirabletargetlinksjul21',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.TargetJul21', verbose_name='Target'),
        ),
        migrations.AddField(
            model_name='desirabletargetlinksjul21',
            name='test_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.GenomicTestJul21', verbose_name='Test Code'),
        ),
    ]
