# Generated by Django 2.2.23 on 2021-11-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngtdc_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desirabletarget',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='desirabletarget',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='genomictest',
            name='cc_id',
        ),
        migrations.RemoveField(
            model_name='genomictest',
            name='citt_id',
        ),
        migrations.RemoveField(
            model_name='genomictest',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='genomictest',
            name='specialist_id',
        ),
        migrations.RemoveField(
            model_name='genomictest',
            name='targets_desirable',
        ),
        migrations.RemoveField(
            model_name='genomictest',
            name='tt_code',
        ),
        migrations.DeleteModel(
            name='CITTComment',
        ),
        migrations.DeleteModel(
            name='CommissioningCategory',
        ),
        migrations.DeleteModel(
            name='DesirableTarget',
        ),
        migrations.DeleteModel(
            name='OptimalFamilyStructure',
        ),
        migrations.DeleteModel(
            name='SpecialistTestGroup',
        ),
    ]
