# Generated by Django 2.2.23 on 2021-07-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngtdc_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomictest',
            name='targets',
        ),
        migrations.CreateModel(
            name='LinkTestToTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.GenomicTest', verbose_name='Test Code')),
                ('test_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngtdc_db.Target', verbose_name='Target')),
            ],
        ),
        migrations.AddField(
            model_name='genomictest',
            name='targets',
            field=models.ManyToManyField(through='ngtdc_db.LinkTestToTarget', to='ngtdc_db.Target', verbose_name='Targets'),
        ),
    ]
