# Generated by Django 2.2.23 on 2021-07-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngtdc_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetjul21',
            name='hgnc_id',
            field=models.CharField(default='Not specified', max_length=50, verbose_name='HGNC ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetnov20',
            name='hgnc_id',
            field=models.CharField(default='Not specified', max_length=50, verbose_name='HGNC ID'),
            preserve_default=False,
        ),
    ]
