# Generated by Django 2.2.23 on 2021-07-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngtdc_db', '0002_auto_20210714_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalindication',
            old_name='cancer_type',
            new_name='cancer_id',
        ),
        migrations.RenameField(
            model_name='genomictest',
            old_name='test_scope',
            new_name='scope_id',
        ),
        migrations.RenameField(
            model_name='genomictest',
            old_name='technology',
            new_name='tech_id',
        ),
        migrations.RenameField(
            model_name='linktesttotarget',
            old_name='test_target',
            new_name='target_id',
        ),
    ]
